apiVersion: v2.edp.epam.com/v1alpha1
kind: Jenkins
metadata:
  name: example-jenkins
spec:
  version: "2.176.3"
  image: "docker-registry.default.svc:5000/edp-cicd-delivery/jenkins"
  volumes:
    - name: "data"
      storageClass: "efs"
      capacity: "1Gi"