apiVersion: v2.edp.epam.com/v1alpha1
kind: Jenkins
metadata:
  name: example-jenkins
spec:
  version: "epamedp/edp-jenkins"
  image: "2.0.0"
  volumes:
    - name: "data"
      storage_class: "efs"
      capacity: "1Gi"
